# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "10"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true
  directories:
    - "node_modules"

notifications:
  email:
    on_failure:
      change
    on_success:
      never

before_install:
  - curl https://yarnpkg.com/install.sh -sSfL | bash -s --
  - export PATH="${HOME}/.yarn/bin:${PATH}"
