name: Build

on:
  push:
    branches:
      - main

jobs:
  build_test_release:
    name: Build, test and release
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Build, lint and test
        run: |
          yarn
          yarn lint
          yarn test
          yarn dist
          yarn flatten
      - name: Release on npm
        run: |
          git config --global "user.email" "${GIT_AUTHOR_EMAIL}"
          git config --global "user.name" "${GIT_AUTHOR_NAME}"
          REPO_URL="$(git remote get-url origin | sed -n "s/https:\/\/github.com\//https:\/\/${GIT_AUTHOR_NAME}:${GH_TOKEN}@github.com\//p")"
          yarn release -r "${REPO_URL}"
        env:
          GIT_AUTHOR_NAME: ffflobot
          GIT_AUTHOR_EMAIL: ffflobot@users.noreply.github.com
          GIT_COMMITTER_NAME: ffflobot
          GIT_COMMITTER_EMAIL: ffflobot@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: "!startsWith(github.event.head_commit.message, 'chore')"
      - name: Release on GitHub
        run: |
          rm .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" > ~/.npmrc
          cd flattened
          sed -i "s/\"name\": \"/\"name\": \"@ffflorian\//" package.json
          npm publish --registry=https://npm.pkg.github.com || true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: "!startsWith(github.event.head_commit.message, 'chore')"
