name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Build and test
        run: |
          yarn
          yarn lint
          yarn test
          yarn dist
          yarn flatten
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
      - name: Release on npm
        run: |
          git config --global "user.email" "${GIT_EMAIL}"
          git config --global "user.name" "${GIT_NAME}"
          REPO_URL="$(git remote get-url origin | sed -n "s/https:\/\/github.com\//https:\/\/${GIT_AUTHOR_NAME}:${GH_TOKEN}@github.com\//p")"
          yarn release -r "${REPO_URL}"
        env:
          GIT_AUTHOR_NAME: ffflobot
          GIT_AUTHOR_EMAIL: ffflobot@users.noreply.github.com
          GIT_COMMITTER_NAME: ffflobot
          GIT_COMMITTER_EMAIL: ffflobot@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
      - name: Release on GitHub
        run: |
          rm .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" > ~/.npmrc
          cd flattened
          npm publish --registry=https://npm.pkg.github.com || true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
